### ISSUE TITLE
Terminologie Aufgaben / Übungen

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS21#10]
von @GAEgeler (entnommen aus #9 )

> zudem sollten wir noch eine gemeinsame terminologie festlegen (zurzeit nicht einheitlich). mein vorschlag: @smwidmer passt das für dich?
> für die übungen: Aufgabe X
> für die musterlösungen: Loesung Aufgabe X
> 
> für ordner struktur in statistik:
> für übung: statistikX_assigment
> für musterlösung: staistikX_solution
> für demo: statistiX_Demo

**Comment by ratnanil** [comment]
Sprichst du hier von der Nomenklatur der Ordnernamen, der Namen der .Rmd files oder die Title innerhalb des Rmd Files?

Bei Prepro haben wir aktuell folgendes System für die Titel:

```
Übung A
  - Aufgabe 1
  - Aufgabe 2
  - Aufgabe 3
Übung B
  - Aufgabe 1
  - ...
```
Wobei jeder Unterrichtsblock (z.B. Prepro 1) wieder bei `A` beginnt.

In Statistik sehe ich folgendes System: 

```
Übung 1
  - Übung 1.1
  - Übung 1.2
  - Übung 1.3
Übung 2
  - Übung 2.1
  - ...
```

ich bin bereit, unsere Nomenklatur anzupassen

**Comment by GAEgeler** [comment]
Genau wegen den Umlauten habe ich den Titel zu Aufgabe 1 angepasst also d.h.
```
Aufgabe 1
  - Aufgabe 1.1
  - Aufgabe 1.2
  - Aufgabe 1.3
Aufgabe 2
  - Aufgabe 2.1
  - ...
```
Ich denke es kann sicher auch zwischen den Blöcken Unterschiede geben, nur innerhalb wäre es sinnvoll dasselbe "System" zu verwenden.
