### ISSUE TITLE
Error knit:  invalid multibyte string

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS21#12]
@ratnanil, beim Kompilieren meines Rmd Muslerloesung_Deskriptive_Analysen erscheint eine Fehlermeldung:

output file: Musterloesung_Desktiptive_Analysen.knit.md

```
Fehler in substring(u, so, so + ml - 1L) : 
  invalid multibyte string, element 1
Ruft auf: <Anonymous> ... regmatches -> Map -> mapply -> <Anonymous> -> substring
Zusätzlich: Warnmeldungen:
1: Problem with `mutate()` column `tre200jx`.
i `tre200jx = as.numeric(tre200jx)`.
i NAs durch Umwandlung erzeugt 
2: Problem with `mutate()` column `rre150j0`.
i `rre150j0 = as.numeric(rre150j0)`.
i NAs durch Umwandlung erzeugt 
3: In grepl("data-distill-preview=", line, fixed = TRUE) :
  Eingabe-Zeichenkette 1 ist ungültig in UTF-8
Ausführung angehalten
```

Die Warnmeldungen ignoriere ich getrost, aber dieser  invalid multibyte string bereitet mir Kopfschmerzen. ;)
Das kompilieren aller anderen Rmd's klappt anstandslos. Auch in diesem Rmd kann ich die einzelnen chunks rendern.

Wie kann ich hier debuggen?

Danke und LG

**Comment by ratnanil** [comment]
wo befindet sich das file genau? hast du es gepusht? ich finde nur folgende files:

```
BE_S_1_Einleitung/Einleitung.Rmd
BE_S_2_Felderhebung_Loesung/Musterloesung_Felderhebung.Rmd
BE_S_2_Felderhebung/Felderhebung.Rmd
BE_S_3_Aufgabenstellung/Aufgabenstellung.Rmd
BE_S_4_Projektierung/Projektierung.Rmd
BE_S_5_Import_Vorverabeitung/Import_Vorverarbeitung.Rmd
BE_S_5_Import_Vorverarbeitung_Loesung/Musterloesung_Import_Vorverarbeitung.Rmd
BE_S_6_Deskriptive_Analysen/Deskriptive_Analysen.Rmd
BE_S_7_Multivariate_Statistik/Multivariate_Statistik.Rmd
```

PS: wenn du code mit ``` umgibst (vorher und nacher, wie bei R Code Chunks) ist er im Issue besser lesbar!

**Comment by hochad** [comment]
das Problem konnte behoben werden, indem ich alle ä und ö mit ae, respektive ae ersetzt habe. 

Wenn ich nun erneut ein ä einfüge, klappt das ganze wieder wie gewohnt.

**Comment by GAEgeler** [comment]
ich meinte rmakdown erwartet immer utf-8 codierte files

**Comment by ratnanil** [comment]
nur wenn man die Einstellungen (https://researchmethods-zhaw.github.io/HS21/Readme.html#rstudio-konfigurieren) so einstellt

> Default Text Encoding: UTF-8 (<- wichtig !)

Hattest du dies schon gemacht, @hochad ?

**Comment by ratnanil** [comment]
@GAEgeler: siehe auch [My Biggest Regret in the knitr Package](https://yihui.org/en/2018/11/biggest-regret-knitr/)

**Comment by GAEgeler** [comment]
@hochad das hilft sonst auch: https://rmd4sci.njtierney.com/common-problems-with-rmarkdown-and-some-solutions.html

**Comment by hochad** [comment]
> 
> 
> nur wenn man die Einstellungen (https://researchmethods-zhaw.github.io/HS21/Readme.html#rstudio-konfigurieren) so einstellt
> 
> > Default Text Encoding: UTF-8 (<- wichtig !)
> 
> Hattest du dies schon gemacht, @hochad ?

Ja, das ist so eingestellt.
