### ISSUE TITLE
Build Website: listing

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS21#13]
@ratnanil, bei builden der WEbsite erhalte ich den Fehler:

````
Fehler: The collection 'fallstudien' does not have an article listing.
(try running render_site() to generate the listing)
Ausf�hrung angehalten

Exited with status 1.
````

Das Fallstudien.Rmd exisitert nach wie vor und darin sehe ich auch das listing. 
Kann es sein, dass dieses Issue mit #12 zusammenhängt?

LG

**Comment by hochad** [comment]
Der Fehler hängt nicht mit Issue #12 zusammen.

**Comment by ratnanil** [comment]
Hallo @hochad : ich habe den Fehler gefunden: Kannst du die neusten Änderungen pullen? Der Fehler war, das @GAEgeler das index.Rmd File gelöscht hatte.

Kannst du den issue schliessen wenn es jetzt klappt?

**Comment by hochad** [comment]
Lieber @ratnanil, jetzt klappt das builden wieder wie gewohnt! Danke für deine schnelle und professionelle Hilfe!
