### ISSUE TITLE
Die Readme page erscheint heute Morgen «blank»

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS21#2]
von @hochad

**Comment by ratnanil** [comment]
ich glaube github streikt gerade und will meine änderungen nicht annehmen, aber das problem sollte morgen gelöst sein 
![DeepinScreenshot_select-area_20210906220244](https://user-images.githubusercontent.com/12532091/132257739-eca589bd-ac8b-4e87-b922-cd9fc4e756a7.png)

**Comment by hochad** [comment]
Funktioniert wieder, danke!
