### ISSUE TITLE
Reihenfolge im Tutorial anpassen

### ISSUE THREAD

**Issue by smwidmer** [ResearchMethods-ZHAW/HS21#28]
Gerne möchte ich den Statistiken Teilen im Tutorial die Reihenfolge der Beiträge anpassen analog zu PrepPro und Infovis also zuerst Demo, dann Aufgabe dann Lösungen. Wie kann das angepasst werden? @ratnanil @KimboGilda

**Comment by ratnanil** [comment]
Für die Reihenfolge der Beiträge sind die Ordnernamen verantwortlich, diese werden Alphabetisch sortiert. Du müsstest also die Ordnernamen so umbenennenen, dass sie in alphabetisch georneter der Reihenfolge entspricht die du dir wünschst. 

Zum Beispiel in "Statistik1_01-Demo", "Statistik1_02-Assignment" und "Statistik1_03-Solution". Dies sieht nicht sehr schön aus, das sehen im wesentlichen aber nur wir. Vielleicht fallen dir auch Ordnernamen ein, die besser passen.

**Comment by smwidmer** [comment]
alles klar. Dann passe ich das bei gelgenheit an. Merci
