### ISSUE TITLE
Fehlermeldung beim knitten

### ISSUE THREAD

**Issue by smwidmer** [ResearchMethods-ZHAW/HS21#29]
Wenn ich die Lösungen (Neu erstelle Ordner solution_stat2.3n / solution_stat2.1.) knitten will erscheint folgende Fehlermeldung:

_Fehler in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 1, column 31
Ruft auf: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Ausführung angehalten_

Wo liegt das Problem?

**Comment by ratnanil** [comment]
Hast du einen ":" im Titel? Um welches Rmd handelt es sich?

**Comment by smwidmer** [comment]
Ja hatte : im Titel nachdem ich den : entfernt habe klappts es einwandrei. Merci
