### ISSUE TITLE
Leider klappt das pushen bei mir nicht. 

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS21#3]
von @hochad
Leider klappt das pushen bei mir nicht. Ich sehe folgende Fehlermeldung: 
![DeepinScreenshot_select-area_20210906145724](https://user-images.githubusercontent.com/12532091/132221127-022241eb-d7b4-41d4-8e91-432a97a63919.png)

wobei meine Loginabgaben, welche ich in der Konsole eingeben muss, sicher korrekt sind.

**Comment by ratnanil** [comment]
du kannst dich nicht mehr mit benutzername und passwort authentifizieren, weil das für github.com zu unsicher ist (siehe auch der Link, der in der Fehlermeldung erscheint: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/)
Lass uns das morgen mal anschauen.

**Comment by hochad** [comment]
wer lesen kann ist klar im vorteil... danke Nils für den Hinweis! Nun klappt alles bestens! =)
