### ISSUE TITLE
.csv files lassen sich nicht mehr downloaden

### ISSUE THREAD

**Issue by smwidmer** [ResearchMethods-ZHAW/HS21#31]
Sämtliche verlinkte files die nicht auf externe Sources zuückgreifen lassen sich nicht mehr herunterladen. 
Wäre gut wenn dieses Problem zeitnah gelöst werden könnte ... 
@ratnanil @KimboGilda

**Comment by smwidmer** [comment]
ich kann die datasets auch auf eine seperate repro (https://github.com/ResearchMethods-ZHAW/datasets) legen und von dort verlinken. Leider habe ich beim versuch das anzupassen gerade in Konflikt verurscht, bevor ich alles anpassen konnte...

**Comment by ratnanil** [comment]
> ich kann die datasets auch auf eine seperate repro (https://github.com/ResearchMethods-ZHAW/datasets) legen und von dort verlinken.

ich denke das wäre eine gute Gelegenheit, dies zu tun. Ich sehe das du einige files auf das dataset repo hochgeladen hast. Ich  habe soeben die urls in den Rmds angepasst (844956f3c0b435766bf1b9b142e641ca22fcf36f) kannst du prüfen ob es nun funktioniert?

**Comment by ratnanil** [comment]
wenn es funktioniert füge ich `/_statistik/**/*.csv` zu `.gitignore` hinzu (siehe #5)

**Comment by GAEgeler** [comment]
bei mir funktioniert es, thx!

ps. bei novanimal files (auf zenodo hochgeladen) dauert der download min. 30sek für 5mb - was ich doch sehr lange finde. vorschläge um das zu verkürzen?

**Comment by smwidmer** [comment]
> 
> 
> > ich kann die datasets auch auf eine seperate repro (https://github.com/ResearchMethods-ZHAW/datasets) legen und von dort verlinken.

Können wir gerne so machen. 

> 
> ich denke das wäre eine gute Gelegenheit, dies zu tun. Ich sehe das du einige files auf das dataset repo hochgeladen hast. Ich habe soeben die urls in den Rmds angepasst ([844956f](https://github.com/ResearchMethods-ZHAW/HS21/commit/844956f3c0b435766bf1b9b142e641ca22fcf36f)) kannst du prüfen ob es nun funktioniert?

Momentan funktioniert bei Übung Statistik 3 der Link zu Ukraine_bearbeitet.csv noch nicht . Auch bei Statistik 4 lassen sich sämtliche csv. noch nicht dowloaden. Kann das wegen Konflikten gerade nicht selber anpassen

**Comment by smwidmer** [comment]
nun sind alle links angepasst und /_statistik/**/*.csv kann zu .gitignorehinzugefügt werden
