### ISSUE TITLE
Lösungen erscheinen nicht im Tutorial

### ISSUE THREAD

**Issue by smwidmer** [ResearchMethods-ZHAW/HS21#32]
Die Lösungen  4.1 und 4.2n (Statistik 4) erscheinen nicht in im Tutorial obwohl ich draft: false gsetzt, geknitted und gepusht habe
@ratnanil @KimboGilda

**Comment by GAEgeler** [comment]
ist nun online, was ich gesehen habe, ist, dass du die tags nicht korrekt gesetzt hast e.g. anstelle von statistik4 hattest du statistik
