### ISSUE TITLE
Rauman 5: MCE

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS21#45]
Hey Nikos! This time, let me give some feedback more in advance. Concerning the MCE Exercise (rauman5):

- why is there a `\newpage` everywhere? Is this an artefact from Dominik? can you remove these?
- where is the data for this exercise?
- why is the TOC included manually, rather than via `toc: true`
- I would remove `functions used in this exercise`, we have never mentioned them in the other exercises
- let's work with `terra`, not `raster`
- if you add any large datasets to the repo, can you make sure that these are ignored in `.gitignore` and also excluded via the rmd's yaml header (resources: excluce: ....tif, see raster_intro.Rmd). otherwise, we are going to clutter our repo (#5)
- can the CRS information be passed as an EPSG code? Otherwise, we would need to introduce the studets to this proj4 notation
- can you include the sample solution of each exercise as code chunks and set `echo = FALSE` for all chunks?

**Comment by KimboGilda** [comment]
I think the only thing missing is the transition to `terra` functions for the solutions. Maybe it would need more time to do so. At least for me. Please have a look and and we can talk tomorrow.

**Comment by ratnanil** [comment]
why do we do this in MCE?

```
ahp_matrix <- ahp_matrix %>% cbind(rowSums(ahp_matrix)) #add row sum
ahp_matrix <- sweep(ahp_matrix, 2, colSums(ahp_matrix), FUN="/") #normalize data
```

**Comment by ratnanil** [comment]
this does not work for me: 

```
> rasterOptions(tolerance = 0.5)
Error in rasterOptions(tolerance = 0.5) : 
  could not find function "rasterOptions"
```

nor does this:

```
weighted_overlay <- (reclass_wind * weights[1]) +
  (reclass_streets_ed * weights[2]) +
  (reclass_ice * weights[3]) +
  (reclass_settlements_ed * weights[4]) +
  (reclass_forests_ed * weights[5]) +
  (reclass_slope * weights[6]) +
  (reclass_protected_areas_ed * weights[7])
Error: [+] extents do not match
```

I tried clipping everything to the minimal exent, but this causes an issue since the rasters are not aligned with each other.

**Comment by ratnanil** [comment]
@KimboGilda: I should be working on something else, can you pull my latest changes and try to find a solution? I suggest we remove all `eval = FALSE` chunk options and run the code locally when kniting the document, since this will reveal such issues much sooner
