### ISSUE TITLE
Beiträge verstecken

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS21#7]
von @hochad 

> Lieber Nils
>Habe ich es richtig verstanden, dass ich im Ordner …\Research-Methods_Fallstudie\HS21\docs\fallstudien einfach die bereits kompilierten Dokumente, welche ich den Studierenden noch nicht zeigen möchte, löschen muss? Wenn ich die zeigen will, kann ich die dann einfach neu kompilieren, oder?

Es gibt noch eine einfachere Methode: Du kannst im yaml-header die die option `draft: true` setzen und dann die webseite neu "builden" (siehe #6)

**Comment by ratnanil** [comment]
@hochad hat das funktioniert? wenn ja kannst du issue gerne schliessen!

**Comment by hochad** [comment]
Perfekt, danke Nils
