### ISSUE TITLE
missing a lot of packages with renv::restore()?

### ISSUE THREAD

**Issue by GAEgeler** [ResearchMethods-ZHAW/HS21#8]
is that possible that all the functions from tidyverse are not on the renv lock.file?

**Comment by ratnanil** [comment]
the entire tidyverse is actually part of the lockfile.. what are you missing?

https://github.com/ResearchMethods-ZHAW/HS21/blob/0a0c5bcee38ba2139fe0f2305e0bcbced58e1ad4/renv.lock#L1159-L1165

**Comment by GAEgeler** [comment]
all of it, even distill package is missing => after renv::restore(), needed all to install manually on my local maschine - does that make sense?

**Comment by ratnanil** [comment]
no, not at all... let's try to solve it via webex?

**Comment by ratnanil** [comment]
@smwidmer @KimboGilda @hochad:

@GAEgeler und ich haben uns die Sache mit `renv` nochmal genauer angeschaut. Bis jetzt hatten wir *alle* Packages von *allen* Rmd Files in renv.lock festgehalten. Das hat dazu geführt, dass wir eine _sehr_ grosse Liste an Packages hatten, die wir alle installieren mussten auch wenn wir diese gar nicht benötigt hatten.

Wir haben uns entschieden, von einem impliziten Ansatz auf einen Expliziten Ansatz zu wechseln. D.h., dass wir in dem File `DESCRIPTION` explizit festhalten, welche Packages es *minimal* braucht um die Website zu "builden" (siehe https://github.com/ResearchMethods-ZHAW/HS21/issues/6#issuecomment-925250983).

**Comment by ratnanil** [comment]
nein musst du nicht. ich habe `renv.lock` jetzt beschränkt auf `distill`, alle anderen Packages sind jetzt nicht synchronisiert. Evt. greifen wir das Thema zu einem späteren Zeitpunkt wieder auf

_Originally posted by @ratnanil in https://github.com/ResearchMethods-ZHAW/HS21/issues/11#issuecomment-927793463_
